from typing import Callable


def censor_message(message: str,
                   censored_words: list[str] = ["@everyone", "@here"]) -> str:
    """Censor the words from a message.

    :param message: the message to censor
    :param censored_words: the list of words to censor
    """
    censored_message = replace_strings(
        message, censored_words, replace_func=lambda word: "#" * len(word))
    return censored_message


def replace_strings(string: str, strings_to_replace: list[str],
                    replace_func: Callable[[str], str]) -> str:
    """Replace occurrences of specific strings in the string with a string generated by the replacing function.

    :param string: the string in which we'll be replacing some strings
    :param strings_to_replace: the strings to replace inside the given string
    :replace_func: the function which returns the replacing string"""
    for word_to_replace in strings_to_replace:
        string = string.replace(word_to_replace, replace_func(word_to_replace))
    return string
